name: Build and Push Docker Image test 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t my-tictac-game .
        docker tag my-tictac-game:latest chaimaaro/my-tictac-game:latest

    - name: Push Docker image
      run: |
        docker push chaimaaro/my-tictac-game:latest

    - name: Set up Docker Compose
      uses: docker/compose-cli-action@v3

    - name: Deploy Docker container
      run: |
        docker run -d -p 8089:8089 chaimaaro/my-tictac-game:latest
